// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zooshop_App1;

#nullable disable

namespace Zooshop_App1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Zooshop_App1.Categories", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Zooshop_App1.Customers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Zooshop_App1.Order_Items", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("orders_id")
                        .HasColumnType("int");

                    b.Property<int>("products_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("orders_id");

                    b.HasIndex("products_id");

                    b.ToTable("Order_Items");
                });

            modelBuilder.Entity("Zooshop_App1.Orders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("order_date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Zooshop_App1.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("categories_id")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("suppliers_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("categories_id");

                    b.HasIndex("suppliers_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Zooshop_App1.Suppliers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Suppliersid")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Suppliersid");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Zooshop_App1.Order_Items", b =>
                {
                    b.HasOne("Zooshop_App1.Orders", "orders_")
                        .WithMany("order_items")
                        .HasForeignKey("orders_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zooshop_App1.Products", "products_")
                        .WithMany("order_items")
                        .HasForeignKey("products_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("orders_");

                    b.Navigation("products_");
                });

            modelBuilder.Entity("Zooshop_App1.Orders", b =>
                {
                    b.HasOne("Zooshop_App1.Customers", "customer_")
                        .WithMany("orders")
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer_");
                });

            modelBuilder.Entity("Zooshop_App1.Products", b =>
                {
                    b.HasOne("Zooshop_App1.Categories", "categories_")
                        .WithMany("products")
                        .HasForeignKey("categories_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zooshop_App1.Suppliers", "suppliers_")
                        .WithMany()
                        .HasForeignKey("suppliers_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categories_");

                    b.Navigation("suppliers_");
                });

            modelBuilder.Entity("Zooshop_App1.Suppliers", b =>
                {
                    b.HasOne("Zooshop_App1.Suppliers", null)
                        .WithMany("suppliers")
                        .HasForeignKey("Suppliersid");
                });

            modelBuilder.Entity("Zooshop_App1.Categories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Zooshop_App1.Customers", b =>
                {
                    b.Navigation("orders");
                });

            modelBuilder.Entity("Zooshop_App1.Orders", b =>
                {
                    b.Navigation("order_items");
                });

            modelBuilder.Entity("Zooshop_App1.Products", b =>
                {
                    b.Navigation("order_items");
                });

            modelBuilder.Entity("Zooshop_App1.Suppliers", b =>
                {
                    b.Navigation("suppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
